// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurnyruSistema.Models;

namespace TurnyruSistema.Migrations
{
    [DbContext(typeof(TurnyruSistemaContext))]
    [Migration("20200427130658_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TurnyruSistema.Models.Organizatorius", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ElPastas");

                    b.Property<string>("Prisijungimas");

                    b.Property<DateTime>("RegistracijosData");

                    b.Property<string>("RodomasVardas");

                    b.Property<string>("Slaptazodis");

                    b.HasKey("Id");

                    b.ToTable("Organizatorius");
                });

            modelBuilder.Entity("TurnyruSistema.Models.Turnyras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrganizatoriusId");

                    b.Property<DateTime>("PabaigosData");

                    b.Property<string>("Pavadinimas");

                    b.Property<DateTime>("PradziosData");

                    b.Property<string>("Vieta");

                    b.HasKey("Id");

                    b.HasIndex("OrganizatoriusId");

                    b.ToTable("Turnyras");
                });

            modelBuilder.Entity("TurnyruSistema.Models.Turnyras", b =>
                {
                    b.HasOne("TurnyruSistema.Models.Organizatorius", "Organizatorius")
                        .WithMany()
                        .HasForeignKey("OrganizatoriusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
