// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurnyruSistema.Models;

namespace TurnyruSistema.Migrations
{
    [DbContext(typeof(TurnyruSistemaContext))]
    [Migration("20200530114153_KompiuteriuZona")]
    partial class KompiuteriuZona
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TurnyruSistema.Models.Komanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ElPastas");

                    b.Property<int>("Laimejimai");

                    b.Property<string>("Paveikslelis");

                    b.Property<int>("Pralaimejimai");

                    b.Property<string>("Prisijungimas");

                    b.Property<DateTime>("RegistracijosData");

                    b.Property<string>("Slaptazodis");

                    b.Property<string>("pavadinimas");

                    b.HasKey("Id");

                    b.ToTable("Komanda");
                });

            modelBuilder.Entity("TurnyruSistema.Models.KompiuteriuZona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KompiuteriuSkaicius");

                    b.Property<string>("Pavadinimas");

                    b.Property<int>("TurnyrasId");

                    b.HasKey("Id");

                    b.HasIndex("TurnyrasId");

                    b.ToTable("KompiuteriuZona");
                });

            modelBuilder.Entity("TurnyruSistema.Models.Organizatorius", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ElPastas");

                    b.Property<string>("Prisijungimas");

                    b.Property<DateTime>("RegistracijosData");

                    b.Property<string>("RodomasVardas");

                    b.Property<string>("Slaptazodis");

                    b.HasKey("Id");

                    b.ToTable("Organizatorius");
                });

            modelBuilder.Entity("TurnyruSistema.Models.Turnyras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrganizatoriusId");

                    b.Property<DateTime>("PabaigosData");

                    b.Property<string>("Pavadinimas");

                    b.Property<DateTime>("PradziosData");

                    b.Property<string>("Vieta");

                    b.HasKey("Id");

                    b.HasIndex("OrganizatoriusId");

                    b.ToTable("Turnyras");
                });

            modelBuilder.Entity("TurnyruSistema.Models.Zaidejas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("komandaId");

                    b.Property<string>("slapyvardis");

                    b.Property<string>("vardas");

                    b.HasKey("Id");

                    b.HasIndex("komandaId");

                    b.ToTable("Zaidejas");
                });

            modelBuilder.Entity("TurnyruSistema.Models.KompiuteriuZona", b =>
                {
                    b.HasOne("TurnyruSistema.Models.Turnyras", "Turnyras")
                        .WithMany()
                        .HasForeignKey("TurnyrasId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TurnyruSistema.Models.Turnyras", b =>
                {
                    b.HasOne("TurnyruSistema.Models.Organizatorius", "Organizatorius")
                        .WithMany()
                        .HasForeignKey("OrganizatoriusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TurnyruSistema.Models.Zaidejas", b =>
                {
                    b.HasOne("TurnyruSistema.Models.Komanda", "komanda")
                        .WithMany("zaidejai")
                        .HasForeignKey("komandaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
